### ISSUE TITLE
Worksheet is too simplistic  Eg- No resistor value or range given.  LED polarity ignored.

### ISSUE THREAD

**Issue by jsavage** [raspberrypilearning/getting-started-with-gpio-zero#3]
I can see these materials are trying to keep things simple and I appreciate that the absolute value is not critical so I am trying not to be too picky but we cant escape the fact that the value of a resistor used does matter.  I would suggest providing at least a nominal value but caveat by saying that this is not critical so long as the value is in the range x to y.  If you want to keep the sheet clean then maybe this additional detail could be hidden behind a mode info type hyperlink or placed on a separate page?

The first image should show the LED 'glowing'

The image of the diode should at least give a clue as to the correct orientation. this sheet should at least indicate the "flat" side even if it does not want to go into + & -

**Comment by MarcScott** [comment]
This resource has been archived and replaced with https://github.com/raspberrypilearning/physical-computing-with-python
