### ISSUE TITLE
GPIOError running on Stretch

### ISSUE THREAD

**Issue by dpritt** [raspberrypilearning/getting-started-with-gpio-zero#8]
I am running GPIOZero on a Raspberry PI with Stretch.

Every few minutes I get the following message in the Python3.5 shell

```
Exception ignored in: <bound method GPIOBase.__del__ of <gpiozero.MCP3008 object using <weakproxy at 0xb3b35d20 to NoneType at 0x3e5788>>>
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/gpiozero/devices.py", line 122, in __del__
    self.close()
  File "/usr/lib/python3/dist-packages/gpiozero/spi_devices.py", line 37, in close
    if self._spi:
ReferenceError: weakly-referenced object no longer exists
```

Please advise how to remedy this.

Regards

Dave

**Comment by lawsie** [comment]
@bennuttall

**Comment by bennuttall** [comment]
@dpritt Can you post the code you tried, not just the error?

**Comment by bennuttall** [comment]
Also please use backticks when entering code, so it looks like this:

```python
for i in range(10):
    print("Hello")
```

**Comment by MarcScott** [comment]
@dpritt I'm going to close this issue. Please feel free to reopen with an example of the failing code if you are still having issues
